// Mocks generated by Mockito 5.2.0 from annotations
// in series/test/helpers/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:convert' as _i16;
import 'dart:typed_data' as _i17;

import 'package:common/common.dart' as _i11;
import 'package:dartz/dartz.dart' as _i3;
import 'package:http/http.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:series/data/datasources/db/database_helper.dart' as _i14;
import 'package:series/data/datasources/tv_local_data_source.dart' as _i8;
import 'package:series/data/datasources/tv_remote_data_source.dart' as _i5;
import 'package:series/data/models/tv/tv_detail_model.dart' as _i2;
import 'package:series/data/models/tv/tv_model.dart' as _i7;
import 'package:series/data/models/tv/tv_table.dart' as _i9;
import 'package:series/domain/entities/tv/tv.dart' as _i12;
import 'package:series/domain/entities/tv/tv_detail.dart' as _i13;
import 'package:series/domain/repositories/tv_repository.dart' as _i10;
import 'package:sqflite_sqlcipher/sqflite.dart' as _i15;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTvDetailResponse_0 extends _i1.Fake implements _i2.TvDetailResponse {
}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

class _FakeResponse_2 extends _i1.Fake implements _i4.Response {}

class _FakeStreamedResponse_3 extends _i1.Fake implements _i4.StreamedResponse {
}

/// A class which mocks [TvRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRemoteDataSource extends _i1.Mock
    implements _i5.TvRemoteDataSource {
  MockTvRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<List<_i7.TvModel>> getNowPlayingTv() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingTv, []),
              returnValue: Future<List<_i7.TvModel>>.value(<_i7.TvModel>[]))
          as _i6.Future<List<_i7.TvModel>>);
  @override
  _i6.Future<List<_i7.TvModel>> getPopularTv() =>
      (super.noSuchMethod(Invocation.method(#getPopularTv, []),
              returnValue: Future<List<_i7.TvModel>>.value(<_i7.TvModel>[]))
          as _i6.Future<List<_i7.TvModel>>);
  @override
  _i6.Future<List<_i7.TvModel>> getTopRated() =>
      (super.noSuchMethod(Invocation.method(#getTopRated, []),
              returnValue: Future<List<_i7.TvModel>>.value(<_i7.TvModel>[]))
          as _i6.Future<List<_i7.TvModel>>);
  @override
  _i6.Future<_i2.TvDetailResponse> getTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvDetail, [id]),
              returnValue:
                  Future<_i2.TvDetailResponse>.value(_FakeTvDetailResponse_0()))
          as _i6.Future<_i2.TvDetailResponse>);
  @override
  _i6.Future<List<_i7.TvModel>> getTvRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
              returnValue: Future<List<_i7.TvModel>>.value(<_i7.TvModel>[]))
          as _i6.Future<List<_i7.TvModel>>);
  @override
  _i6.Future<List<_i7.TvModel>> searchSeries(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchSeries, [query]),
              returnValue: Future<List<_i7.TvModel>>.value(<_i7.TvModel>[]))
          as _i6.Future<List<_i7.TvModel>>);
}

/// A class which mocks [TvLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvLocalDataSource extends _i1.Mock implements _i8.TvLocalDataSource {
  MockTvLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<void> cacheNowPlayingTv(List<_i9.TvTable>? movies) =>
      (super.noSuchMethod(Invocation.method(#cacheNowPlayingTv, [movies]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> cachePopularTv(List<_i9.TvTable>? movies) =>
      (super.noSuchMethod(Invocation.method(#cachePopularTv, [movies]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<void> cacheTopRatedTv(List<_i9.TvTable>? movies) =>
      (super.noSuchMethod(Invocation.method(#cacheTopRatedTv, [movies]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<List<_i9.TvTable>> getCachedNowPlayingTv() =>
      (super.noSuchMethod(Invocation.method(#getCachedNowPlayingTv, []),
              returnValue: Future<List<_i9.TvTable>>.value(<_i9.TvTable>[]))
          as _i6.Future<List<_i9.TvTable>>);
  @override
  _i6.Future<List<_i9.TvTable>> getCachedPopularTv() =>
      (super.noSuchMethod(Invocation.method(#getCachedPopularTv, []),
              returnValue: Future<List<_i9.TvTable>>.value(<_i9.TvTable>[]))
          as _i6.Future<List<_i9.TvTable>>);
  @override
  _i6.Future<List<_i9.TvTable>> getCachedTopRatedTv() =>
      (super.noSuchMethod(Invocation.method(#getCachedTopRatedTv, []),
              returnValue: Future<List<_i9.TvTable>>.value(<_i9.TvTable>[]))
          as _i6.Future<List<_i9.TvTable>>);
  @override
  _i6.Future<String> insertTvWatchlist(_i9.TvTable? movie) =>
      (super.noSuchMethod(Invocation.method(#insertTvWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<String> removeTvWatchlist(_i9.TvTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeTvWatchlist, [movie]),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<List<_i9.TvTable>> getWatchlistTv() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTv, []),
              returnValue: Future<List<_i9.TvTable>>.value(<_i9.TvTable>[]))
          as _i6.Future<List<_i9.TvTable>>);
  @override
  _i6.Future<_i9.TvTable?> getTvById(int? id) => (super.noSuchMethod(
      Invocation.method(#getTvById, [id]),
      returnValue: Future<_i9.TvTable?>.value()) as _i6.Future<_i9.TvTable?>);
}

/// A class which mocks [TvRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvRepository extends _i1.Mock implements _i10.TvRepository {
  MockTvRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.Either<_i11.Failure, List<_i12.TV>>> getNowPlayingTv() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingTv, []),
          returnValue: Future<_i3.Either<_i11.Failure, List<_i12.TV>>>.value(
              _FakeEither_1<_i11.Failure, List<_i12.TV>>())) as _i6
          .Future<_i3.Either<_i11.Failure, List<_i12.TV>>>);
  @override
  _i6.Future<_i3.Either<_i11.Failure, List<_i12.TV>>> getPopularTv() =>
      (super.noSuchMethod(Invocation.method(#getPopularTv, []),
          returnValue: Future<_i3.Either<_i11.Failure, List<_i12.TV>>>.value(
              _FakeEither_1<_i11.Failure, List<_i12.TV>>())) as _i6
          .Future<_i3.Either<_i11.Failure, List<_i12.TV>>>);
  @override
  _i6.Future<_i3.Either<_i11.Failure, List<_i12.TV>>> getTopRated() =>
      (super.noSuchMethod(Invocation.method(#getTopRated, []),
          returnValue: Future<_i3.Either<_i11.Failure, List<_i12.TV>>>.value(
              _FakeEither_1<_i11.Failure, List<_i12.TV>>())) as _i6
          .Future<_i3.Either<_i11.Failure, List<_i12.TV>>>);
  @override
  _i6.Future<_i3.Either<_i11.Failure, _i13.TvDetail>> getTvDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvDetail, [id]),
          returnValue: Future<_i3.Either<_i11.Failure, _i13.TvDetail>>.value(
              _FakeEither_1<_i11.Failure, _i13.TvDetail>())) as _i6
          .Future<_i3.Either<_i11.Failure, _i13.TvDetail>>);
  @override
  _i6.Future<_i3.Either<_i11.Failure, List<_i12.TV>>> getTvRecommendations(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvRecommendations, [id]),
          returnValue: Future<_i3.Either<_i11.Failure, List<_i12.TV>>>.value(
              _FakeEither_1<_i11.Failure, List<_i12.TV>>())) as _i6
          .Future<_i3.Either<_i11.Failure, List<_i12.TV>>>);
  @override
  _i6.Future<_i3.Either<_i11.Failure, List<_i12.TV>>> searchSeries(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchSeries, [query]),
          returnValue: Future<_i3.Either<_i11.Failure, List<_i12.TV>>>.value(
              _FakeEither_1<_i11.Failure, List<_i12.TV>>())) as _i6
          .Future<_i3.Either<_i11.Failure, List<_i12.TV>>>);
  @override
  _i6.Future<_i3.Either<_i11.Failure, String>> saveTvWatchlist(
          _i13.TvDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#saveTvWatchlist, [movie]),
              returnValue: Future<_i3.Either<_i11.Failure, String>>.value(
                  _FakeEither_1<_i11.Failure, String>()))
          as _i6.Future<_i3.Either<_i11.Failure, String>>);
  @override
  _i6.Future<_i3.Either<_i11.Failure, String>> removeTvWatchlist(
          _i13.TvDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#removeTvWatchlist, [movie]),
              returnValue: Future<_i3.Either<_i11.Failure, String>>.value(
                  _FakeEither_1<_i11.Failure, String>()))
          as _i6.Future<_i3.Either<_i11.Failure, String>>);
  @override
  _i6.Future<_i3.Either<_i11.Failure, List<_i12.TV>>> getWatchlistTv() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTv, []),
          returnValue: Future<_i3.Either<_i11.Failure, List<_i12.TV>>>.value(
              _FakeEither_1<_i11.Failure, List<_i12.TV>>())) as _i6
          .Future<_i3.Either<_i11.Failure, List<_i12.TV>>>);
  @override
  _i6.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
}

/// A class which mocks [DatabaseSeriesHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseSeriesHelper extends _i1.Mock
    implements _i14.DatabaseSeriesHelper {
  MockDatabaseSeriesHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i15.Database?> get database =>
      (super.noSuchMethod(Invocation.getter(#database),
              returnValue: Future<_i15.Database?>.value())
          as _i6.Future<_i15.Database?>);
  @override
  _i6.Future<void> insertTvCacheTransaction(
          List<_i9.TvTable>? series, String? category) =>
      (super.noSuchMethod(
          Invocation.method(#insertTvCacheTransaction, [series, category]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  _i6.Future<List<Map<String, dynamic>>> getCacheTv(String? category) =>
      (super.noSuchMethod(Invocation.method(#getCacheTv, [category]),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i6.Future<List<Map<String, dynamic>>>);
  @override
  _i6.Future<int> clearTvCache(String? category) =>
      (super.noSuchMethod(Invocation.method(#clearTvCache, [category]),
          returnValue: Future<int>.value(0)) as _i6.Future<int>);
  @override
  _i6.Future<int> insertTvWatchlist(_i9.TvTable? series) =>
      (super.noSuchMethod(Invocation.method(#insertTvWatchlist, [series]),
          returnValue: Future<int>.value(0)) as _i6.Future<int>);
  @override
  _i6.Future<int> removeTvWatchlist(_i9.TvTable? movie) =>
      (super.noSuchMethod(Invocation.method(#removeTvWatchlist, [movie]),
          returnValue: Future<int>.value(0)) as _i6.Future<int>);
  @override
  _i6.Future<Map<String, dynamic>?> getTvById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i6.Future<Map<String, dynamic>?>);
  @override
  _i6.Future<List<Map<String, dynamic>>> getWatchlistTv() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTv, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i6.Future<List<Map<String, dynamic>>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i11.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<bool> get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected),
          returnValue: Future<bool>.value(false)) as _i6.Future<bool>);
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i4.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i4.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_2()))
          as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_2()))
          as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i16.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_2()))
          as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i16.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_2()))
          as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i16.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_2()))
          as _i6.Future<_i4.Response>);
  @override
  _i6.Future<_i4.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i16.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i4.Response>.value(_FakeResponse_2()))
          as _i6.Future<_i4.Response>);
  @override
  _i6.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i6.Future<String>);
  @override
  _i6.Future<_i17.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i17.Uint8List>.value(_i17.Uint8List(0)))
          as _i6.Future<_i17.Uint8List>);
  @override
  _i6.Future<_i4.StreamedResponse> send(_i4.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue:
                  Future<_i4.StreamedResponse>.value(_FakeStreamedResponse_3()))
          as _i6.Future<_i4.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
}
