// Mocks generated by Mockito 5.2.0 from annotations
// in ditonton/test/presentation/pages/tv/tv_nowplaying_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:core/core.dart' as _i3;
import 'package:core/domain/usecases/tv/get_tv_now_playing.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetTvNowPlayingMovies_0 extends _i1.Fake
    implements _i2.GetTvNowPlayingMovies {}

/// A class which mocks [NowPlayingTvNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockNowPlayingTvNotifier extends _i1.Mock
    implements _i3.NowPlayingTvNotifier {
  MockNowPlayingTvNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTvNowPlayingMovies get getTvNowPlayingMovies =>
      (super.noSuchMethod(Invocation.getter(#getTvNowPlayingMovies),
              returnValue: _FakeGetTvNowPlayingMovies_0())
          as _i2.GetTvNowPlayingMovies);
  @override
  _i3.RequestState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _i3.RequestState.Empty) as _i3.RequestState);
  @override
  List<_i3.TV> get movies =>
      (super.noSuchMethod(Invocation.getter(#movies), returnValue: <_i3.TV>[])
          as List<_i3.TV>);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i4.Future<void> fetchNowPlaying() =>
      (super.noSuchMethod(Invocation.method(#fetchNowPlaying, []),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  void addListener(_i5.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i5.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
